### ISSUE TITLE
UX design // mark selected items in menu

### ISSUE THREAD

**Issue by DL3RTL** [llinkz/directTDoA#7]
First of all: Thank you so much for your great job! this software is awesome!
In the upper menu bar there are items to be clicked on to be selected.
For example the type of the algorithm.

Unfortunately in the UX design of the GUI there are no markers that identify what is actually selected.
I would be a great improvement to implement like bold font for selected items in the menue.

**Comment by llinkz** [comment]
Hi
I'll see what I can do for this
You probably notice, the default TDoA algo settings are shown at software startup (5th line)

**Comment by llinkz** [comment]
Hi
Solution to bold items in menus was more complicated than adding a legend on the map
It is a simple solution which I hope will satisfy you.

73

**Comment by DL3RTL** [comment]
Thank you so much. That workaround is fine and helps our team. Great job! 73s, Daniel, speaker of bandwacht.de

**Comment by llinkz** [comment]
Thanks Daniel

73
