### ISSUE TITLE
Stop recording sometimes not possible

### ISSUE THREAD

**Issue by DL8LAQ** [llinkz/directTDoA#8]
Sometimes the recording cannot be stopped. Maybe if recording gets too long. I recently forget to stop after 15 - 30 seconds and tried it after 1100 seconds due to contest activity, but failed.
Ok, just found out that "Start TDoA proc" will do the trick!!!

**Comment by llinkz** [comment]
Hi

Ok noted

BTW I have put a hard-coded recording duration variable to cover the case the user forget to (or can't) click to stop recording
This is a 120 seconds limit

line
358                                  str(FREQUENCY), '-L', str(lpcut), '-H', str(hpcut), '-m', 'iq', '--tlimit', '120',

No worries then, the kiwirecorder.py socket will close itself and each IQ files will not be greater than approx. 6MB

Regards
