### ISSUE TITLE
Bug: Nodes purged when stop listen mode

### ISSUE THREAD

**Issue by DL8LAQ** [llinkz/directTDoA#9]
Hi!
All selected nodes get purged when I stop the listen mode!
73, Norbert

**Comment by llinkz** [comment]
Thanks for that bug report Norbert
I'll check why

73

**Comment by llinkz** [comment]
Hi Norbert

Should be fixed in 7.10

73

**Comment by DL8LAQ** [comment]
It is fixed now! Thank you!
